### ISSUE TITLE
'\\n'; or more backslash  match to ExpressionStatement(CharacterLiteral)

### ISSUE THREAD

**Issue by NewOag** [lezer-parser/java#7]
**JDK compile failed because of too many characters in character literal**

**Comment by marijnh** [comment]
Note that rejecting every invalid program is not a goal of this grammar. Still, the logic in there was a bit weird (probably inspired by a bogus test case inherited from tree-sitter). Attached patch removes the test and tightens it up a bit.

**Comment by NewOag** [comment]
Thank you very much for your patch o.0
