### ISSUE TITLE
Umlaute in variable names

### ISSUE THREAD

**Issue by Entkenntnis** [lezer-parser/java#9]
Java allows all unicode-letters in variable names, not only latin letters. Is there a chance to include these characters in the identifier regex?

Otherwise, this is how valid java code would look like:

![grafik](https://github.com/user-attachments/assets/f8c9588a-8b6a-4397-96e8-df6923066174)

My current approach is to copy-paste the grammar and change it from

https://github.com/lezer-parser/java/blob/14901c5f4aead1cdd28d2d05007f130b055f5ab6/src/java.grammar#L712-L714

to

```
  identifier { $[a-z_$äöü] $[a-zA-Z0-9_$äöüÄÖÜß]* }

  capitalIdentifier { $[A-ZÄÖÜ] $[a-zA-Z0-9_$äöüÄÖÜß]* }
```

**Comment by marijnh** [comment]
Attached patch should help with this.

**Comment by Entkenntnis** [comment]
Thank you, it's working now!
